### PR TITLE
Added notes, categorized, added delete and edit methods

### PR DESCRIPTION
**Pull request by Ivefan**

### CODE REVIEW

**Review by Hanicef — CHANGES_REQUESTED** [review]
Due to my data access layer, the `getAllLicenseSummary()` functions is adviced to be removed as license summaries are abstracted from the JAX-RS interface.

**Comment by Ivefan** [comment]
Ready for merge

**Review by Hanicef — CHANGES_REQUESTED** [review]
Replace Exception catches with more specific ones

**Review by Hanicef — APPROVED** [review]
Great quality!

**Pull request merged**
